#shardingjdbc读写分离配置
spring:
  shardingsphere:
    datasource: ## 主从数据源
      names: sharding0, sharding1
      sharding0:  ## 主数据源，负责写操作
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.38.134:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      sharding1:  ## 主数据源，负责读操作
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.38.135:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    masterslave:
      name: ms
      master-data-source-name: sharding0
      slave-data-source-names: sharding1
      # random 随机，round_robin 轮询
      load-balance-algorithm-type: round_robin
    props:
      sql:
        show: true
